/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-111422-g886c1ffb5d-20230712"
#endif /* AVUTIL_FFVERSION_H */
